version: '3.4'

services:
  logstash:
    #image: docker.elastic.co/elasticsearch/elasticsearch-oss:${ES_VERSION}
    container_name: logstash
    image: docker.elastic.co/logstash/logstash-oss:${ES_VERSION}
    environment:
      PATH_CONFIG: "/usr/share/logstash/pipeline" # default
      ES_HOST: ${ES_HOST}
      ES_PORT: ${ES_PORT}
    volumes:
      - ./logstash/pipeline:/usr/share/logstash/pipeline:ro
    logging:
        driver: none
networks:
  default:
    external:
      name: ${DC_NETWORK}
