version: '2'

services:
  logstash:
    #image: docker.elastic.co/elasticsearch/elasticsearch-oss:${ES_VERSION}
    container_name: ${DC_PREFIX}-logstash
    image: docker.elastic.co/logstash/logstash-oss:${ES_VERSION}
    environment:
      PATH_CONFIG: "/usr/share/logstash/pipeline" # default
    volumes:
      - ./logstash/pipeline:/usr/share/logstash/pipeline:ro
    ports:
      - "1025:1025/udp"
      - "127.0.0.1:5000:5000"
      - "127.0.0.1:9600:9600"
networks:
  default:
    external:
      name: ${DC_NETWORK}
