version: '3.4'
services:
  nginx-production:
    image: nginx-production:${APP_VERSION}
    build:
      context: ${NGINX}
      target: production
      dockerfile: Dockerfile
      args:
        app_name: ${APP}
        app_ver: ${APP_VERSION}
        http_proxy: ${http_proxy}
        https_proxy: ${https_proxy}
        no_proxy: ${no_proxy}

    container_name: nginx-production

    environment:
      - APP
      - ES_PROXY_PATH
      - ES_HOST
      - ES_INDEX
      - ES_PORT
      - BACKEND_HOST
      - BACKEND_PORT
      - PORT
      - KIBANA_PORT
      - KIBANA_HOST
      - LOGSTASH_HOST
    ports:
      - "$PORT:80"
      #restart: always
    volumes:
      - ./nginx/apache2:/etc/nginx/apache2
      - ${FRONTEND_STATIC_USER}:/usr/share/nginx/html/export/user
    logging:
        #driver: none
        options:
          max-size: "10m"
          max-file: "1"
networks:
  default:
    external:
      name: ${DC_NETWORK}
