version: '2'

services:
  backend:
    build:
      context: ${BACKEND}
      dockerfile: Dockerfile
      args:
        http_proxy: ${http_proxy}
        https_proxy: ${https_proxy}
        no_proxy: ${no_proxy}
    image: ${APP}-backend-${EXEC_ENV}:${APP_VERSION}
    container_name: ${APP}-backend-${EXEC_ENV}
    volumes:
      - ${BACKEND}/:/app/
    expose:
      - ${BACKEND_PORT}
    environment:
      BACKEND_PORT: ${BACKEND_PORT}
  tika:
    image: logicalspark/docker-tikaserver
    container_name: ${DC_PREFIX}-tika
    expose:
      - "9998"
    environment:
      - http_proxy
      - https_proxy
      - no_proxy

networks:
  default:
    external:
      name: ${DC_NETWORK}
