version: '3.4'
services:
  nginx-production:
    image: ${APP}-nginx-production:${APP_VERSION}
    build:
      context: ${NGINX}
      target: production
      dockerfile: Dockerfile
      args:
        app_name: ${APP}
        app_ver: ${APP_VERSION}


    container_name: ${DC_PREFIX}-nginx-production

    environment:
      - APP
      - ES_PROXY_PATH
      - ES_HOST
      - ES_INDEX
      - ES_PORT
      - BACKEND_HOST
      - BACKEND_PORT
      - PORT
      - KIBANA_PORT
      - KIBANA_HOST
      - LOGSTASH_HOST
    ports:
      - "80:80"
    #restart: always

networks:
  default:
    external:
      name: ${DC_NETWORK}
