version: '3.4'
services:
  frontend-build:
    build:
      context: ${FRONTEND}
      dockerfile: Dockerfile
      target: build
      args:
        http_proxy: ${http_proxy}
        https_proxy: ${https_proxy}
        no_proxy: ${no_proxy}
    image: ${APP}-frontend-build:${APP_VERSION}
    container_name: frontend-build
    environment:
      - http_proxy
      - https_proxy
      - no_proxy
    env_file:
      - $ENV_FILE


networks:
  default:
    external:
      name: ${DC_NETWORK}
