version: '3.4'

# this docker configuation is for dev use only

services:
  traefik:
    image: ${APP}-traefik-${EXEC_ENV}:${APP_VERSION}
    container_name: ${APP}-traefik-${EXEC_ENV}
    build:
      context: ${TRAEFIK_PATH}
      target: ${EXEC_ENV}
      dockerfile: Dockerfile
    environment:
      - TRAEFIK_LOG_LEVEL=${LOG_LEVEL}
      - TRAEFIK_ENTRYPOINTS_http=true
      - TRAEFIK_ENTRYPOINTS_http_ADDRESS=:80
      - TRAEFIK_ENTRYPOINTS_https=true
      - TRAEFIK_ENTRYPOINTS_https_ADDRESS=:443
      - TRAEFIK_ENTRYPOINTS_livereload=true
      - TRAEFIK_ENTRYPOINTS_livereload_ADDRESS=:35729
      - TRAEFIK_PROVIDERS_DOCKER=true
      - TRAEFIK_PROVIDERS_DOCKER_ENDPOINT=unix:///var/run/docker.sock
      - TRAEFIK_PROVIDERS_DOCKER_EXPOSEDBYDEFAULT=false
    ports:
      - ${PORT}:80
      - 443:443
      - 35729:35729
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./traefik/acme.json:/acme.json

  frontend-development:
    build:
      context: ${FRONTEND}
      dockerfile: Dockerfile
      target: dev
      args:
        http_proxy: ${http_proxy}
        https_proxy: ${https_proxy}
        no_proxy: ${no_proxy}
        npm_registry: ${NPM_REGISTRY}
        sass_registry: ${SASS_REGISTRY}
        MIRROR_DEBIAN: ${MIRROR_DEBIAN}
        app_path: /${APP}
        app_name: ${APP}
        app_ver: ${APP_VERSION}
        NPM_FIX: ${NPM_FIX}
        NPM_LATEST: ${NPM_LATEST}
        NPM_GIT: ${NPM_GIT}
        NPM_VERBOSE: ${NPM_VERBOSE}
    #image: ${DOCKER_USERNAME}/${DC_PREFIX}-frontend-development:${APP_VERSION}
    image: ${APP}-frontend-development:${APP_VERSION}
    container_name: ${APP}-frontend-development
    environment:
      APP: ${APP}
      PORT: 5000
      HOST: 0.0.0.0
      ES_PROXY_PATH: ${ES_PROXY_PATH}
    volumes:
      - ${FRONTEND}/public:/${APP}/public
      - ${FRONTEND}/.eslintrc.js:/${APP}/.eslintrc.js
      - ${FRONTEND}/rollup.config.js:/${APP}/rollup.config.js
      - ${FRONTEND}/src:/${APP}/src/
      - /${APP}/node_modules

networks:
  default:
    external:
      name: ${DC_NETWORK}
