version: '3.4'

services:
  kibana:
    container_name: ${KIBANA_HOST}
    image: docker.elastic.co/kibana/kibana:${ES_VERSION}
    environment:
      SERVER_NAME: kibana
      ELASTICSEARCH_HOSTS: http://${ES_HOST}:${ES_PORT}
      SERVER_BASEPATH: /kibana # if behind nginx
    external_links:
      - browser_elasticsearch:elasticsearch
    ports:
      - "5601:${KIBANA_PORT}"
    logging:
        driver: none
networks:
  default:
    external:
      name: ${DC_NETWORK}
