version: '2'

services:
  elasticsearch:
    #image: docker.elastic.co/elasticsearch/elasticsearch-oss:${ES_VERSION}
    container_name: ${DC_PREFIX}-elasticsearch
    build:
      context: ./elasticsearch
      dockerfile: Dockerfile
      args:
        - http_proxy=${http_proxy}
        - ES_VERSION=${ES_VERSION}
    environment:
      - cluster.name=matchid-cluster
      - bootstrap.memory_lock=true
      - TAKE_FILE_OWNERSHIP=true
      - "ES_JAVA_OPTS=-Xms%M -Xmx%M"
      - discovery.type=single-node
    ulimits:
      memlock:
        soft: -1
        hard: -1
    # mem_limit: %MM
    volumes:
     - ${ES_DATA}/node1:/usr/share/elasticsearch/data
     - ${ES_DATA}/extra:/usr/share/elasticsearch/data/extra
     #- ./elasticsearch/config:/usr/share/elasticsearch/config
     #- ${DATA_PATH}:/data
    ports:
       - "9200:9200"

networks:
  default:
    external:
      name: ${DC_NETWORK}
