name: basic-test-backend

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Build the Docker image
        run: make backend-dev
      - name: test
        run: make test
